// <auto-generated />
using System;
using Mattin.Project.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mattin.Project.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250219200836_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Mattin.Project.Core.Models.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kungsgatan 1, 111 43 Stockholm",
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Email = "info@mattin-lassei.se",
                            Name = "Mattin-Lassei Group AB",
                            PhoneNumber = "08-123 45 67"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Sveavägen 10, 111 57 Stockholm",
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Email = "contact@techinnovators.se",
                            Name = "Tech Innovators AB",
                            PhoneNumber = "08-987 65 43"
                        });
                });

            modelBuilder.Entity("Mattin.Project.Core.Models.Entities.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProjectManagerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StatusId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Description = "Komplett redesign av företagets webbplats med fokus på användarupplevelse",
                            EndDate = new DateTime(2025, 4, 20, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            HourlyRate = 1200m,
                            ProjectManagerId = 1,
                            ProjectNumber = "2024-001",
                            ServiceId = 1,
                            StartDate = new DateTime(2025, 1, 20, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            StatusId = 2,
                            Title = "Webbplats Redesign",
                            TotalPrice = 480000m
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Description = "Utveckling av ny e-handelsplattform med integration mot befintliga system",
                            EndDate = new DateTime(2025, 6, 4, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            HourlyRate = 1100m,
                            ProjectManagerId = 2,
                            ProjectNumber = "2024-002",
                            ServiceId = 1,
                            StartDate = new DateTime(2025, 3, 6, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            StatusId = 1,
                            Title = "E-handelsplattform",
                            TotalPrice = 880000m
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 1,
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Description = "Utveckling av mobilapp för intern kommunikation",
                            EndDate = new DateTime(2025, 4, 5, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            HourlyRate = 1300m,
                            ProjectManagerId = 3,
                            ProjectNumber = "2024-003",
                            ServiceId = 2,
                            StartDate = new DateTime(2025, 2, 4, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            StatusId = 2,
                            Title = "App-utveckling",
                            TotalPrice = 416000m
                        });
                });

            modelBuilder.Entity("Mattin.Project.Core.Models.Entities.ProjectManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectManagers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Department = "Development",
                            Email = "anna.andersson@mattin-lassei.se",
                            IsActive = true,
                            Name = "Anna Andersson",
                            PhoneNumber = "070-123 45 67"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Department = "Design",
                            Email = "erik.eriksson@mattin-lassei.se",
                            IsActive = true,
                            Name = "Erik Eriksson",
                            PhoneNumber = "070-234 56 78"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Department = "Mobile Development",
                            Email = "maria.nilsson@mattin-lassei.se",
                            IsActive = true,
                            Name = "Maria Nilsson",
                            PhoneNumber = "070-345 67 89"
                        });
                });

            modelBuilder.Entity("Mattin.Project.Core.Models.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 50000m,
                            Category = "Development",
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Description = "Full-stack web development services including frontend and backend",
                            HourlyRate = 1200m,
                            IsActive = true,
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 75000m,
                            Category = "Development",
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Description = "Native and cross-platform mobile application development",
                            HourlyRate = 1300m,
                            IsActive = true,
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 35000m,
                            Category = "Design",
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Description = "User interface and experience design for digital products",
                            HourlyRate = 1100m,
                            IsActive = true,
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 65000m,
                            Category = "Infrastructure",
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Description = "Setup and management of cloud infrastructure and DevOps practices",
                            HourlyRate = 1400m,
                            IsActive = true,
                            Name = "Cloud Infrastructure"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 45000m,
                            Category = "Security",
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Description = "Comprehensive security assessment and penetration testing",
                            HourlyRate = 1500m,
                            IsActive = true,
                            Name = "Security Audit"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 55000m,
                            Category = "Analytics",
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Description = "Business intelligence and data analytics solutions",
                            HourlyRate = 1250m,
                            IsActive = true,
                            Name = "Data Analytics"
                        });
                });

            modelBuilder.Entity("Mattin.Project.Core.Models.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Description = "Projektet har inte påbörjats än",
                            IsDefault = true,
                            Name = "Ej påbörjat",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Description = "Projektet är under utveckling",
                            IsDefault = false,
                            Name = "Pågående",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2025, 2, 19, 20, 8, 36, 93, DateTimeKind.Utc).AddTicks(5600),
                            Description = "Projektet är färdigt",
                            IsDefault = false,
                            Name = "Avslutat",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Mattin.Project.Core.Models.Entities.ProjectEntity", b =>
                {
                    b.HasOne("Mattin.Project.Core.Models.Entities.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mattin.Project.Core.Models.Entities.ProjectManager", "ProjectManager")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mattin.Project.Core.Models.Entities.Service", "Service")
                        .WithMany("Projects")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mattin.Project.Core.Models.Entities.Status", "Status")
                        .WithMany("Projects")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ProjectManager");

                    b.Navigation("Service");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Mattin.Project.Core.Models.Entities.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Mattin.Project.Core.Models.Entities.ProjectManager", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Mattin.Project.Core.Models.Entities.Service", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Mattin.Project.Core.Models.Entities.Status", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
